Review the Documentation
marsiitr/Robotic-Arm-simulation pull request #1
Opened 2022-07-25 18:47 UTC by Aviral2002

2022-08-07 19:02 UTC, Nageshbansal reviewed
1. add a report in the``` Poster and Report ```directory
2. all images in readme should be of same size and you need to add these images in ```<p></p>``` tags to align them in the center
3. add links of the mentor's github profile also

2022-08-14 21:14 UTC, Aviral2002 commented
I have made the changes.
Please review.

2022-08-19 13:00 UTC, SanjeevKrishnan commented
> I have made the changes. Please review.

@Nageshbansal Look into this and tag me once the repo is ready for merge.

2022-08-25 17:49 UTC, Nageshbansal requested changes
1. Add some videos for e.g. simulation of the Model in Gazebo, and Solidworks.
2. File names should be according to the given Documentation Guidelines.
3. Remove `log` files from the `src` directory.
4. Justify the text in README.md for e.g usage of the`<h3>` for sub-headings.
5. Installation or Setup Instructions in README.md
6.  Decrease the dimensions of the images.
Let me know when you're done with changes.

2022-08-26 14:36 UTC, Aviral2002 commented
I have made the changes.
Please review.

2026-05-24 13:07 UTC, merged